//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.WSUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSUsuarios.WebServiceAD_UsuariosSoap")]
    public interface WebServiceAD_UsuariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento identificacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuario", ReplyAction="*")]
        ServiciosWeb.WSUsuarios.CrearUsuarioResponse CrearUsuario(ServiciosWeb.WSUsuarios.CrearUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.CrearUsuarioResponse> CrearUsuarioAsync(ServiciosWeb.WSUsuarios.CrearUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento identificacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        ServiciosWeb.WSUsuarios.ActualizarUsuarioResponse ActualizarUsuario(ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ActualizarUsuarioResponse> ActualizarUsuarioAsync(ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento identificacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        ServiciosWeb.WSUsuarios.EliminarUsuarioResponse EliminarUsuario(ServiciosWeb.WSUsuarios.EliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.EliminarUsuarioResponse> EliminarUsuarioAsync(ServiciosWeb.WSUsuarios.EliminarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarUsuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuarios", ReplyAction="*")]
        ServiciosWeb.WSUsuarios.ListarUsuariosResponse ListarUsuarios(ServiciosWeb.WSUsuarios.ListarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ListarUsuariosResponse> ListarUsuariosAsync(ServiciosWeb.WSUsuarios.ListarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento identificacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuario", ReplyAction="*")]
        ServiciosWeb.WSUsuarios.ObtenerUsuarioResponse ObtenerUsuario(ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ObtenerUsuarioResponse> ObtenerUsuarioAsync(ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.CrearUsuarioRequestBody Body;
        
        public CrearUsuarioRequest() {
        }
        
        public CrearUsuarioRequest(ServiciosWeb.WSUsuarios.CrearUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombreUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombreCompleto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        public CrearUsuarioRequestBody() {
        }
        
        public CrearUsuarioRequestBody(string identificacion, string nombreUsuario, string nombreCompleto, string telefono, string contrasena) {
            this.identificacion = identificacion;
            this.nombreUsuario = nombreUsuario;
            this.nombreCompleto = nombreCompleto;
            this.telefono = telefono;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.CrearUsuarioResponseBody Body;
        
        public CrearUsuarioResponse() {
        }
        
        public CrearUsuarioResponse(ServiciosWeb.WSUsuarios.CrearUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CrearUsuarioResponseBody {
        
        public CrearUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.ActualizarUsuarioRequestBody Body;
        
        public ActualizarUsuarioRequest() {
        }
        
        public ActualizarUsuarioRequest(ServiciosWeb.WSUsuarios.ActualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombreUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombreCompleto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        public ActualizarUsuarioRequestBody() {
        }
        
        public ActualizarUsuarioRequestBody(string identificacion, string nombreUsuario, string nombreCompleto, string telefono, string contrasena) {
            this.identificacion = identificacion;
            this.nombreUsuario = nombreUsuario;
            this.nombreCompleto = nombreCompleto;
            this.telefono = telefono;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.ActualizarUsuarioResponseBody Body;
        
        public ActualizarUsuarioResponse() {
        }
        
        public ActualizarUsuarioResponse(ServiciosWeb.WSUsuarios.ActualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActualizarUsuarioResponseBody {
        
        public ActualizarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.EliminarUsuarioRequestBody Body;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(ServiciosWeb.WSUsuarios.EliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identificacion;
        
        public EliminarUsuarioRequestBody() {
        }
        
        public EliminarUsuarioRequestBody(string identificacion) {
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.EliminarUsuarioResponseBody Body;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(ServiciosWeb.WSUsuarios.EliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarUsuarioResponseBody {
        
        public EliminarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.ListarUsuariosRequestBody Body;
        
        public ListarUsuariosRequest() {
        }
        
        public ListarUsuariosRequest(ServiciosWeb.WSUsuarios.ListarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarUsuariosRequestBody {
        
        public ListarUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.ListarUsuariosResponseBody Body;
        
        public ListarUsuariosResponse() {
        }
        
        public ListarUsuariosResponse(ServiciosWeb.WSUsuarios.ListarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiciosWeb.WSUsuarios.Usuario[] ListarUsuariosResult;
        
        public ListarUsuariosResponseBody() {
        }
        
        public ListarUsuariosResponseBody(ServiciosWeb.WSUsuarios.Usuario[] ListarUsuariosResult) {
            this.ListarUsuariosResult = ListarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuario", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.ObtenerUsuarioRequestBody Body;
        
        public ObtenerUsuarioRequest() {
        }
        
        public ObtenerUsuarioRequest(ServiciosWeb.WSUsuarios.ObtenerUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string identificacion;
        
        public ObtenerUsuarioRequestBody() {
        }
        
        public ObtenerUsuarioRequestBody(string identificacion) {
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.WSUsuarios.ObtenerUsuarioResponseBody Body;
        
        public ObtenerUsuarioResponse() {
        }
        
        public ObtenerUsuarioResponse(ServiciosWeb.WSUsuarios.ObtenerUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiciosWeb.WSUsuarios.Usuario ObtenerUsuarioResult;
        
        public ObtenerUsuarioResponseBody() {
        }
        
        public ObtenerUsuarioResponseBody(ServiciosWeb.WSUsuarios.Usuario ObtenerUsuarioResult) {
            this.ObtenerUsuarioResult = ObtenerUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAD_UsuariosSoapChannel : ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAD_UsuariosSoapClient : System.ServiceModel.ClientBase<ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap>, ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap {
        
        public WebServiceAD_UsuariosSoapClient() {
        }
        
        public WebServiceAD_UsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAD_UsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAD_UsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAD_UsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.WSUsuarios.CrearUsuarioResponse ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.CrearUsuario(ServiciosWeb.WSUsuarios.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuario(request);
        }
        
        public void CrearUsuario(string identificacion, string nombreUsuario, string nombreCompleto, string telefono, string contrasena) {
            ServiciosWeb.WSUsuarios.CrearUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.CrearUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.CrearUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.nombreCompleto = nombreCompleto;
            inValue.Body.telefono = telefono;
            inValue.Body.contrasena = contrasena;
            ServiciosWeb.WSUsuarios.CrearUsuarioResponse retVal = ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).CrearUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.CrearUsuarioResponse> ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.CrearUsuarioAsync(ServiciosWeb.WSUsuarios.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.CrearUsuarioResponse> CrearUsuarioAsync(string identificacion, string nombreUsuario, string nombreCompleto, string telefono, string contrasena) {
            ServiciosWeb.WSUsuarios.CrearUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.CrearUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.CrearUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.nombreCompleto = nombreCompleto;
            inValue.Body.telefono = telefono;
            inValue.Body.contrasena = contrasena;
            return ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).CrearUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.WSUsuarios.ActualizarUsuarioResponse ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.ActualizarUsuario(ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuario(request);
        }
        
        public void ActualizarUsuario(string identificacion, string nombreUsuario, string nombreCompleto, string telefono, string contrasena) {
            ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.ActualizarUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.nombreCompleto = nombreCompleto;
            inValue.Body.telefono = telefono;
            inValue.Body.contrasena = contrasena;
            ServiciosWeb.WSUsuarios.ActualizarUsuarioResponse retVal = ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).ActualizarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ActualizarUsuarioResponse> ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.ActualizarUsuarioAsync(ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ActualizarUsuarioResponse> ActualizarUsuarioAsync(string identificacion, string nombreUsuario, string nombreCompleto, string telefono, string contrasena) {
            ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.ActualizarUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.ActualizarUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.nombreCompleto = nombreCompleto;
            inValue.Body.telefono = telefono;
            inValue.Body.contrasena = contrasena;
            return ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).ActualizarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.WSUsuarios.EliminarUsuarioResponse ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.EliminarUsuario(ServiciosWeb.WSUsuarios.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public void EliminarUsuario(string identificacion) {
            ServiciosWeb.WSUsuarios.EliminarUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.EliminarUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.EliminarUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            ServiciosWeb.WSUsuarios.EliminarUsuarioResponse retVal = ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).EliminarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.EliminarUsuarioResponse> ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.EliminarUsuarioAsync(ServiciosWeb.WSUsuarios.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.EliminarUsuarioResponse> EliminarUsuarioAsync(string identificacion) {
            ServiciosWeb.WSUsuarios.EliminarUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.EliminarUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.EliminarUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            return ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).EliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.WSUsuarios.ListarUsuariosResponse ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.ListarUsuarios(ServiciosWeb.WSUsuarios.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuarios(request);
        }
        
        public ServiciosWeb.WSUsuarios.Usuario[] ListarUsuarios() {
            ServiciosWeb.WSUsuarios.ListarUsuariosRequest inValue = new ServiciosWeb.WSUsuarios.ListarUsuariosRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.ListarUsuariosRequestBody();
            ServiciosWeb.WSUsuarios.ListarUsuariosResponse retVal = ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).ListarUsuarios(inValue);
            return retVal.Body.ListarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ListarUsuariosResponse> ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.ListarUsuariosAsync(ServiciosWeb.WSUsuarios.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ListarUsuariosResponse> ListarUsuariosAsync() {
            ServiciosWeb.WSUsuarios.ListarUsuariosRequest inValue = new ServiciosWeb.WSUsuarios.ListarUsuariosRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.ListarUsuariosRequestBody();
            return ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).ListarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.WSUsuarios.ObtenerUsuarioResponse ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.ObtenerUsuario(ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuario(request);
        }
        
        public ServiciosWeb.WSUsuarios.Usuario ObtenerUsuario(string identificacion) {
            ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.ObtenerUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            ServiciosWeb.WSUsuarios.ObtenerUsuarioResponse retVal = ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).ObtenerUsuario(inValue);
            return retVal.Body.ObtenerUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ObtenerUsuarioResponse> ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap.ObtenerUsuarioAsync(ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.WSUsuarios.ObtenerUsuarioResponse> ObtenerUsuarioAsync(string identificacion) {
            ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest inValue = new ServiciosWeb.WSUsuarios.ObtenerUsuarioRequest();
            inValue.Body = new ServiciosWeb.WSUsuarios.ObtenerUsuarioRequestBody();
            inValue.Body.identificacion = identificacion;
            return ((ServiciosWeb.WSUsuarios.WebServiceAD_UsuariosSoap)(this)).ObtenerUsuarioAsync(inValue);
        }
    }
}
