//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceAdmin.WSadmin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSadmin.WSA2Soap")]
    public interface WSA2Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crear_usuario", ReplyAction="*")]
        WebServiceAdmin.WSadmin.crear_usuarioResponse crear_usuario(WebServiceAdmin.WSadmin.crear_usuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crear_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.crear_usuarioResponse> crear_usuarioAsync(WebServiceAdmin.WSadmin.crear_usuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editar_usuario", ReplyAction="*")]
        WebServiceAdmin.WSadmin.editar_usuarioResponse editar_usuario(WebServiceAdmin.WSadmin.editar_usuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editar_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.editar_usuarioResponse> editar_usuarioAsync(WebServiceAdmin.WSadmin.editar_usuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listar_usuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listar_usuarios", ReplyAction="*")]
        WebServiceAdmin.WSadmin.listar_usuariosResponse listar_usuarios(WebServiceAdmin.WSadmin.listar_usuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listar_usuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.listar_usuariosResponse> listar_usuariosAsync(WebServiceAdmin.WSadmin.listar_usuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listar_usuario", ReplyAction="*")]
        WebServiceAdmin.WSadmin.listar_usuarioResponse listar_usuario(WebServiceAdmin.WSadmin.listar_usuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listar_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.listar_usuarioResponse> listar_usuarioAsync(WebServiceAdmin.WSadmin.listar_usuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_usuario", ReplyAction="*")]
        WebServiceAdmin.WSadmin.borrar_usuarioResponse borrar_usuario(WebServiceAdmin.WSadmin.borrar_usuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/borrar_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.borrar_usuarioResponse> borrar_usuarioAsync(WebServiceAdmin.WSadmin.borrar_usuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crear_usuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crear_usuario", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.crear_usuarioRequestBody Body;
        
        public crear_usuarioRequest() {
        }
        
        public crear_usuarioRequest(WebServiceAdmin.WSadmin.crear_usuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crear_usuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre_usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre_completo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contra;
        
        public crear_usuarioRequestBody() {
        }
        
        public crear_usuarioRequestBody(string nombre_usuario, string nombre_completo, string contra) {
            this.nombre_usuario = nombre_usuario;
            this.nombre_completo = nombre_completo;
            this.contra = contra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crear_usuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crear_usuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.crear_usuarioResponseBody Body;
        
        public crear_usuarioResponse() {
        }
        
        public crear_usuarioResponse(WebServiceAdmin.WSadmin.crear_usuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crear_usuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string crear_usuarioResult;
        
        public crear_usuarioResponseBody() {
        }
        
        public crear_usuarioResponseBody(string crear_usuarioResult) {
            this.crear_usuarioResult = crear_usuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editar_usuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editar_usuario", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.editar_usuarioRequestBody Body;
        
        public editar_usuarioRequest() {
        }
        
        public editar_usuarioRequest(WebServiceAdmin.WSadmin.editar_usuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editar_usuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre_usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre_completo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contra;
        
        public editar_usuarioRequestBody() {
        }
        
        public editar_usuarioRequestBody(string nombre_usuario, string nombre_completo, string contra) {
            this.nombre_usuario = nombre_usuario;
            this.nombre_completo = nombre_completo;
            this.contra = contra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editar_usuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editar_usuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.editar_usuarioResponseBody Body;
        
        public editar_usuarioResponse() {
        }
        
        public editar_usuarioResponse(WebServiceAdmin.WSadmin.editar_usuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editar_usuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string editar_usuarioResult;
        
        public editar_usuarioResponseBody() {
        }
        
        public editar_usuarioResponseBody(string editar_usuarioResult) {
            this.editar_usuarioResult = editar_usuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listar_usuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listar_usuarios", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.listar_usuariosRequestBody Body;
        
        public listar_usuariosRequest() {
        }
        
        public listar_usuariosRequest(WebServiceAdmin.WSadmin.listar_usuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listar_usuariosRequestBody {
        
        public listar_usuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listar_usuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listar_usuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.listar_usuariosResponseBody Body;
        
        public listar_usuariosResponse() {
        }
        
        public listar_usuariosResponse(WebServiceAdmin.WSadmin.listar_usuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listar_usuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listar_usuariosResult;
        
        public listar_usuariosResponseBody() {
        }
        
        public listar_usuariosResponseBody(string listar_usuariosResult) {
            this.listar_usuariosResult = listar_usuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listar_usuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listar_usuario", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.listar_usuarioRequestBody Body;
        
        public listar_usuarioRequest() {
        }
        
        public listar_usuarioRequest(WebServiceAdmin.WSadmin.listar_usuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listar_usuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre_usuario;
        
        public listar_usuarioRequestBody() {
        }
        
        public listar_usuarioRequestBody(string nombre_usuario) {
            this.nombre_usuario = nombre_usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listar_usuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listar_usuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.listar_usuarioResponseBody Body;
        
        public listar_usuarioResponse() {
        }
        
        public listar_usuarioResponse(WebServiceAdmin.WSadmin.listar_usuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listar_usuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listar_usuarioResult;
        
        public listar_usuarioResponseBody() {
        }
        
        public listar_usuarioResponseBody(string listar_usuarioResult) {
            this.listar_usuarioResult = listar_usuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class borrar_usuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="borrar_usuario", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.borrar_usuarioRequestBody Body;
        
        public borrar_usuarioRequest() {
        }
        
        public borrar_usuarioRequest(WebServiceAdmin.WSadmin.borrar_usuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class borrar_usuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre_usuario;
        
        public borrar_usuarioRequestBody() {
        }
        
        public borrar_usuarioRequestBody(string nombre_usuario) {
            this.nombre_usuario = nombre_usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class borrar_usuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="borrar_usuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAdmin.WSadmin.borrar_usuarioResponseBody Body;
        
        public borrar_usuarioResponse() {
        }
        
        public borrar_usuarioResponse(WebServiceAdmin.WSadmin.borrar_usuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class borrar_usuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string borrar_usuarioResult;
        
        public borrar_usuarioResponseBody() {
        }
        
        public borrar_usuarioResponseBody(string borrar_usuarioResult) {
            this.borrar_usuarioResult = borrar_usuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSA2SoapChannel : WebServiceAdmin.WSadmin.WSA2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSA2SoapClient : System.ServiceModel.ClientBase<WebServiceAdmin.WSadmin.WSA2Soap>, WebServiceAdmin.WSadmin.WSA2Soap {
        
        public WSA2SoapClient() {
        }
        
        public WSA2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSA2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSA2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSA2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAdmin.WSadmin.crear_usuarioResponse WebServiceAdmin.WSadmin.WSA2Soap.crear_usuario(WebServiceAdmin.WSadmin.crear_usuarioRequest request) {
            return base.Channel.crear_usuario(request);
        }
        
        public string crear_usuario(string nombre_usuario, string nombre_completo, string contra) {
            WebServiceAdmin.WSadmin.crear_usuarioRequest inValue = new WebServiceAdmin.WSadmin.crear_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.crear_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            inValue.Body.nombre_completo = nombre_completo;
            inValue.Body.contra = contra;
            WebServiceAdmin.WSadmin.crear_usuarioResponse retVal = ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).crear_usuario(inValue);
            return retVal.Body.crear_usuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.crear_usuarioResponse> WebServiceAdmin.WSadmin.WSA2Soap.crear_usuarioAsync(WebServiceAdmin.WSadmin.crear_usuarioRequest request) {
            return base.Channel.crear_usuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.crear_usuarioResponse> crear_usuarioAsync(string nombre_usuario, string nombre_completo, string contra) {
            WebServiceAdmin.WSadmin.crear_usuarioRequest inValue = new WebServiceAdmin.WSadmin.crear_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.crear_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            inValue.Body.nombre_completo = nombre_completo;
            inValue.Body.contra = contra;
            return ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).crear_usuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAdmin.WSadmin.editar_usuarioResponse WebServiceAdmin.WSadmin.WSA2Soap.editar_usuario(WebServiceAdmin.WSadmin.editar_usuarioRequest request) {
            return base.Channel.editar_usuario(request);
        }
        
        public string editar_usuario(string nombre_usuario, string nombre_completo, string contra) {
            WebServiceAdmin.WSadmin.editar_usuarioRequest inValue = new WebServiceAdmin.WSadmin.editar_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.editar_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            inValue.Body.nombre_completo = nombre_completo;
            inValue.Body.contra = contra;
            WebServiceAdmin.WSadmin.editar_usuarioResponse retVal = ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).editar_usuario(inValue);
            return retVal.Body.editar_usuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.editar_usuarioResponse> WebServiceAdmin.WSadmin.WSA2Soap.editar_usuarioAsync(WebServiceAdmin.WSadmin.editar_usuarioRequest request) {
            return base.Channel.editar_usuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.editar_usuarioResponse> editar_usuarioAsync(string nombre_usuario, string nombre_completo, string contra) {
            WebServiceAdmin.WSadmin.editar_usuarioRequest inValue = new WebServiceAdmin.WSadmin.editar_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.editar_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            inValue.Body.nombre_completo = nombre_completo;
            inValue.Body.contra = contra;
            return ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).editar_usuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAdmin.WSadmin.listar_usuariosResponse WebServiceAdmin.WSadmin.WSA2Soap.listar_usuarios(WebServiceAdmin.WSadmin.listar_usuariosRequest request) {
            return base.Channel.listar_usuarios(request);
        }
        
        public string listar_usuarios() {
            WebServiceAdmin.WSadmin.listar_usuariosRequest inValue = new WebServiceAdmin.WSadmin.listar_usuariosRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.listar_usuariosRequestBody();
            WebServiceAdmin.WSadmin.listar_usuariosResponse retVal = ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).listar_usuarios(inValue);
            return retVal.Body.listar_usuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.listar_usuariosResponse> WebServiceAdmin.WSadmin.WSA2Soap.listar_usuariosAsync(WebServiceAdmin.WSadmin.listar_usuariosRequest request) {
            return base.Channel.listar_usuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.listar_usuariosResponse> listar_usuariosAsync() {
            WebServiceAdmin.WSadmin.listar_usuariosRequest inValue = new WebServiceAdmin.WSadmin.listar_usuariosRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.listar_usuariosRequestBody();
            return ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).listar_usuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAdmin.WSadmin.listar_usuarioResponse WebServiceAdmin.WSadmin.WSA2Soap.listar_usuario(WebServiceAdmin.WSadmin.listar_usuarioRequest request) {
            return base.Channel.listar_usuario(request);
        }
        
        public string listar_usuario(string nombre_usuario) {
            WebServiceAdmin.WSadmin.listar_usuarioRequest inValue = new WebServiceAdmin.WSadmin.listar_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.listar_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            WebServiceAdmin.WSadmin.listar_usuarioResponse retVal = ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).listar_usuario(inValue);
            return retVal.Body.listar_usuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.listar_usuarioResponse> WebServiceAdmin.WSadmin.WSA2Soap.listar_usuarioAsync(WebServiceAdmin.WSadmin.listar_usuarioRequest request) {
            return base.Channel.listar_usuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.listar_usuarioResponse> listar_usuarioAsync(string nombre_usuario) {
            WebServiceAdmin.WSadmin.listar_usuarioRequest inValue = new WebServiceAdmin.WSadmin.listar_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.listar_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            return ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).listar_usuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAdmin.WSadmin.borrar_usuarioResponse WebServiceAdmin.WSadmin.WSA2Soap.borrar_usuario(WebServiceAdmin.WSadmin.borrar_usuarioRequest request) {
            return base.Channel.borrar_usuario(request);
        }
        
        public string borrar_usuario(string nombre_usuario) {
            WebServiceAdmin.WSadmin.borrar_usuarioRequest inValue = new WebServiceAdmin.WSadmin.borrar_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.borrar_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            WebServiceAdmin.WSadmin.borrar_usuarioResponse retVal = ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).borrar_usuario(inValue);
            return retVal.Body.borrar_usuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.borrar_usuarioResponse> WebServiceAdmin.WSadmin.WSA2Soap.borrar_usuarioAsync(WebServiceAdmin.WSadmin.borrar_usuarioRequest request) {
            return base.Channel.borrar_usuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAdmin.WSadmin.borrar_usuarioResponse> borrar_usuarioAsync(string nombre_usuario) {
            WebServiceAdmin.WSadmin.borrar_usuarioRequest inValue = new WebServiceAdmin.WSadmin.borrar_usuarioRequest();
            inValue.Body = new WebServiceAdmin.WSadmin.borrar_usuarioRequestBody();
            inValue.Body.nombre_usuario = nombre_usuario;
            return ((WebServiceAdmin.WSadmin.WSA2Soap)(this)).borrar_usuarioAsync(inValue);
        }
    }
}
